"""change invoice number unique to composite business and invoice number

Revision ID: 0ef373e7815c
Revises: 706260d8ebf1
Create Date: 2026-10-05 06:32:52.053410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef373e7815c'
down_revision: Union[str, Sequence[str], None] = '706260d8ebf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invoices_invoice_number_key'), 'invoices', type_='unique')
    op.create_unique_constraint('uix_business_id_invoice_number', 'invoices', ['business_id', 'invoice_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_business_id_invoice_number', 'invoices', type_='unique')
    op.create_unique_constraint(op.f('invoices_invoice_number_key'), 'invoices', ['invoice_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
