"""add users, suppliers, purchases, voice_logs, and gstr1_exports

Revision ID: 706260d8ebf1
Revises: dec30e161430
Create Date: 2026-10-05 05:53:47.391925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '706260d8ebf1'
down_revision: Union[str, Sequence[str], None] = 'dec30e161430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('gstr1_exports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('total_invoices', sa.Integer(), nullable=True),
    sa.Column('total_b2b', sa.Integer(), nullable=True),
    sa.Column('total_b2c', sa.Integer(), nullable=True),
    sa.Column('json_file_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('bill_number', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_transaction_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('raw_transcript', sa.Text(), nullable=True),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('input_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('businesses', 'gstin',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('businesses', 'voice_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('businesses', 'offline_mode',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('businesses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_foreign_key(None, 'businesses', 'users', ['owner_user_id'], ['id'])
    op.alter_column('customers', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('customers', 'customer_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('customers_business_id_fkey'), 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'businesses', ['business_id'], ['id'])
    op.alter_column('expenses', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('expenses', 'expense_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('expenses_business_id_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'businesses', ['business_id'], ['id'])
    op.alter_column('invoice_items', 'invoice_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('invoice_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoice_items', 'gst_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('invoice_items', 'discount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoice_items', 'taxable_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoice_items', 'cgst_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoice_items', 'sgst_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoice_items', 'igst_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoice_items', 'line_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.drop_constraint(op.f('invoice_items_invoice_id_fkey'), 'invoice_items', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_items', 'invoices', ['invoice_id'], ['id'])
    op.alter_column('invoices', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('invoices', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('invoices', 'invoice_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoices', 'discount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoices', 'taxable_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoices', 'cgst_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoices', 'sgst_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoices', 'igst_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoices', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('invoices', 'input_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('invoices', 'sync_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_unique_constraint(None, 'invoices', ['invoice_number'])
    op.drop_constraint(op.f('invoices_business_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'businesses', ['business_id'], ['id'])
    op.alter_column('ledger_entries', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ledger_entries', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ledger_entries', 'debit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('ledger_entries', 'credit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('ledger_entries', 'entry_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(op.f('ledger_entries_business_id_fkey'), 'ledger_entries', type_='foreignkey')
    op.create_foreign_key(None, 'ledger_entries', 'businesses', ['business_id'], ['id'])
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('payments', 'payment_mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('payments_invoice_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'invoices', ['invoice_id'], ['id'])
    op.alter_column('products', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('products', 'gst_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('products', 'stock_quantity',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('products_business_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_business_id_fkey'), 'products', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('products', 'stock_quantity',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('products', 'gst_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('products', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_invoice_id_fkey'), 'payments', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('payments', 'payment_mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.UUID(),
               nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'ledger_entries', type_='foreignkey')
    op.create_foreign_key(op.f('ledger_entries_business_id_fkey'), 'ledger_entries', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ledger_entries', 'entry_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('ledger_entries', 'credit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('ledger_entries', 'debit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('ledger_entries', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ledger_entries', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_business_id_fkey'), 'invoices', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'invoices', type_='unique')
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('invoices', 'sync_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('invoices', 'input_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('invoices', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoices', 'igst_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoices', 'sgst_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoices', 'cgst_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoices', 'taxable_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoices', 'discount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoices', 'invoice_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('invoices', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('invoices', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_items_invoice_id_fkey'), 'invoice_items', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.alter_column('invoice_items', 'line_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoice_items', 'igst_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoice_items', 'sgst_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoice_items', 'cgst_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoice_items', 'taxable_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoice_items', 'discount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoice_items', 'gst_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoice_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('invoice_items', 'invoice_id',
               existing_type=sa.UUID(),
               nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_business_id_fkey'), 'expenses', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('expenses', 'expense_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('expenses', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key(op.f('customers_business_id_fkey'), 'customers', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('customers', 'customer_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('customers', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.alter_column('businesses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('businesses', 'offline_mode',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('businesses', 'voice_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('businesses', 'gstin',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.drop_table('voice_transaction_logs')
    op.drop_table('purchases')
    op.drop_table('suppliers')
    op.drop_table('gstr1_exports')
    op.drop_table('users')
    # ### end Alembic commands ###
